blank_issues_enabled: false
contact_links:
  - name: Report an issue to JIRA
    url: https://www.jenkins.io/participate/report-issue/redirect/#21428
    about: Please report new issues of this plugin to JIRA, not to GitHub.
  - name: View open issues in JIRA
    url: https://issues.jenkins.io/issues/?jql=resolution%20is%20EMPTY%20and%20component%3D21428
    about: View the open issues of this plugin at issues.jenkins.io.
  - name: Issue tracking policy
    url: https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/README.md#issue-tracking-where-file-new-issues
    about: Existing issues in GitHub will be migrated to JIRA.
